services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile

  productservice:
    image: productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile

  orderservice:
    image: orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
