version: '3.8'

services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - backend

  productservice:
    image: productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - backend

  orderservice:
    image: orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - backend

  paymentservice:
    image: paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - backend

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - backend
    depends_on:
      - userservice
      - productservice
      - orderservice
      - paymentservice

networks:
  backend:
    driver: bridge
